apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      shareProcessNamespace: true
      containers:
      - name: squid
        image: evgenyalekseev/squid:v1.1
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
        ports:
        - containerPort: 3128
        volumeMounts:
          - mountPath: /etc/squid-conf/conf.d
            name: config-rules
          - mountPath: /etc/squid-conf/acl
            name: config-acl
      - name: sidecar
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600;echo 'test shared pipe'; done"]
        volumeMounts:
          - mountPath: /etc/squid-conf/conf.d
            name: config-rules
          - mountPath: /etc/squid-conf/acl
            name: config-acl
      volumes:
        - name: config-rules
          configMap:
            name: squid-rules
        - name: config-acl
          configMap:
            name: squid-acl