apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: evgenyalekseev/squid:5.0
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
        ports:
        - containerPort: 3128
        volumeMounts:
          - mountPath: /etc/squid/conf.d
            name: config-rules
          - mountPath: /etc/squid/acl
            name: config-acl
      volumes:
        - name: config-rules
          configMap:
            name: squid-rules
        - name: config-acl
          configMap:
            name: squid-acl