apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-rules
data:
  deny.conf: |-
    acl deny_dst url_regex "/etc/squid-conf/acl/dst_deny.acl"
    http_access allow deny_dst
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-acl
data:
  dst_deny.acl: |-
    ^https:\/\/github.com\/saby-integration\/.*$
    info.cern.ch
    columbia.edu
    cisco.com
