apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: evgenyalekseev/squid:2.0
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
        ports:
        - containerPort: 3128
        volumeMounts:
          - mountPath: /etc/squid
            name: config
      volumes:
        - name: config
          configMap:
            name: squid