apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-rules
data:
  deny.conf: |-

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-acl
data:
  dts_deny.acl: |-
    ^https:\/\/github.com\/saby-integration\/.*$
